repos:
  # General checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        name: Check files end with a newline character
      - id: trailing-whitespace
        name: Remove trailing whitespace
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-executables-have-shebangs
        name: Check executable files have a shebang
      - id: check-shebang-scripts-are-executable
        name: Check scripts with a shebang are executable
      - id: check-added-large-files
        name: Don't allow adding large files
      - id: no-commit-to-branch
        name: Prevent committing to main
        args: [--branch, main]

  # Python
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
        name: Validate Python
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: Sort Python imports
        args: [--profile, black]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        name: Format Python
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: Lint Python
        args: [--ignore, "E501,F401"]

  # YAML
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
        name: Validate YAML

  # JSON
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-json
        name: Validate JSON

  # TOML
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
        name: Validate TOML

  # Docker
  - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
    rev: v0.1.0
    hooks:
      - id: dockerfilelint
        name: Lint Dockerfiles
        files: ".*\\.dockerfile"

  # Javascript
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.23.0
    hooks:
      - id: eslint
        name: Lint Javascript
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.0
    hooks:
      - id: prettier
        name: Format Javascript
# Octave
# pipx run --spec miss_hit mh_style --fix **/*.m
