name: Run benchmarks

on:
  - push

jobs:
  run-benchmarks:
    strategy:
      matrix:
        language:
          - julia
          - crystal
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --tag ${{ matrix.language }} .
      - name: Run benchmarks
        run: |
          docker run \
          --workdir /github/workspace \
          --rm \
          --volume (pwd)"/../results/${{ matrix.language }}":/results \
          ${{ matrix.language }}
      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.language }}-benchmark-results
          path: output/test/code-coverage.html
