name: Run benchmarks

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  get-languages:
    runs-on: ubuntu-latest
    outputs:
      languages: ${{ steps.get-languages.outputs.languages }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Get list of languages
        id: get-languages
        run: echo "::set-output name=languages::[\"$(ls ./benchmarks | tr "\n" "\t" | sed 's/\t$//' | sed -E 's/\t/","/g')\"]"
  run-benchmarks:
    needs: [get-languages]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ${{ fromJSON(needs.get-languages.outputs.languages) }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --tag=${{ matrix.language }} benchmarks/${{ matrix.language }}
      - name: Run benchmarks
        run: docker run --volume=$PWD/results/${{ matrix.language }}:/results ${{ matrix.language }}
      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.language }}-benchmark-results
          path: results/${{ matrix.language }}
