name: Run benchmarks

on:
  push:
    branches:
      - main
  pull_request:
      

jobs:
  run-benchmarks:
    strategy:
      matrix:
        language:
          - crystal
          - julia
          - nim
          - python
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Build docker image
        run: docker build --tag=${{ matrix.language }} ${{ matrix.language }}
      - name: Run benchmarks
        run: |
          mkdir -p results/${{ matrix.language }}
          docker run \
          --volume=$PWD/results/${{ matrix.language }}:/results \
          ${{ matrix.language }}
      - name: Upload benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.language }}-benchmark-results
          path: results/${{ matrix.language }}
